define(P_Trigger, "trigger")
define(P_Reset, "reset")
define(P_Set, "set")
define(P_Clock, "clock")
define(P_Looped, "looped")
define(P_Stepped, "stepped")
define(P_Step, "step")
define(P_StepTrigger, "steptrigger")
